FROM node:20-alpine
WORKDIR /app

COPY package*.json ./
COPY apps/api/package.json ./apps/api/
COPY apps/webhook-receiver/package.json ./apps/webhook-receiver/
COPY apps/notification-worker/package.json ./apps/notification-worker/
COPY apps/discord-bot/package.json ./apps/discord-bot/

RUN npm install

COPY tsconfig*.json ./
COPY libs ./libs
COPY scripts ./scripts

CMD ["sh", "-c", "npm run migration:run && npm run seed:run"]