FROM node:20-alpine
WORKDIR /app

COPY package*.json ./
COPY apps/api/package.json ./apps/api/
COPY apps/webhook-receiver/package.json ./apps/webhook-receiver/
COPY apps/notification-worker/package.json ./apps/notification-worker/
COPY apps/discord-bot/package.json ./apps/discord-bot/

RUN npm ci --workspaces=false --include-workspace-root

COPY tsconfig*.json ./
COPY libs ./libs
COPY scripts ./scripts

CMD ["npm", "run", "migration:run"]