FROM node:20-alpine
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY libs/database ./libs/database
COPY scripts/migrate.ts ./scripts/
COPY tsconfig.json ./

CMD ["npx", "ts-node", "-r", "tsconfig-paths/register", "scripts/migrate.ts"]