import { MigrationInterface, QueryRunner } from "typeorm";

export class FixColumnNames1778950576719 implements MigrationInterface {
    name = 'FixColumnNames1778950576719'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "twitch_streamer_events" DROP CONSTRAINT "UQ_1b150333a53b55767e13f367a8d"`);
        await queryRunner.query(`ALTER TABLE "discord_notification_destinations" DROP COLUMN "streamerEventId"`);
        await queryRunner.query(`ALTER TABLE "discord_notification_destinations" DROP COLUMN "channelId"`);
        await queryRunner.query(`ALTER TABLE "discord_notification_destinations" DROP COLUMN "guildId"`);
        await queryRunner.query(`ALTER TABLE "discord_notification_destinations" DROP COLUMN "webhookUrl"`);
        await queryRunner.query(`ALTER TABLE "discord_notification_destinations" DROP COLUMN "messagePayload"`);
        await queryRunner.query(`ALTER TABLE "discord_notification_destinations" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "discord_notification_destinations" DROP COLUMN "creditCost"`);
        await queryRunner.query(`ALTER TABLE "twitch_apps" DROP CONSTRAINT "UQ_25ea1660099082d7896311453fb"`);
        await queryRunner.query(`ALTER TABLE "twitch_apps" DROP COLUMN "clientId"`);
        await queryRunner.query(`ALTER TABLE "twitch_apps" DROP COLUMN "tokenExpiresAt"`);
        await queryRunner.query(`ALTER TABLE "twitch_apps" DROP COLUMN "currentCost"`);
        await queryRunner.query(`ALTER TABLE "twitch_apps" DROP COLUMN "maxCost"`);
        await queryRunner.query(`ALTER TABLE "twitch_apps" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "twitch_apps" DROP COLUMN "webhookSecret"`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer_events" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer_events" DROP CONSTRAINT "UQ_b03926b83345af03988b91047ea"`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer_events" DROP COLUMN "subscriptionId"`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer_events" DROP COLUMN "streamerId"`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer_events" DROP COLUMN "twitchAppId"`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer_events" DROP COLUMN "eventStatus"`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer" DROP CONSTRAINT "UQ_2d84676a48249a92cf693422c26"`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer" DROP COLUMN "twitchLogin"`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer" DROP COLUMN "displayName"`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer" DROP COLUMN "broadcasterId"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "displayName"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_ae4a93a6b25195ccc2a97e13f0d"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "discordId"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "refreshToken"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "discordAccessToken"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "discordRefreshToken"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "publicCreditsUsed"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "privateCreditsUsed"`);
        await queryRunner.query(`ALTER TABLE "discord_notification_destinations" ADD "credit_cost" numeric(3,1) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "discord_notification_destinations" ADD "channel_id" character varying`);
        await queryRunner.query(`ALTER TABLE "discord_notification_destinations" ADD "guild_id" character varying`);
        await queryRunner.query(`ALTER TABLE "discord_notification_destinations" ADD "webhook_url" character varying`);
        await queryRunner.query(`ALTER TABLE "discord_notification_destinations" ADD "message_payload" jsonb`);
        await queryRunner.query(`ALTER TABLE "discord_notification_destinations" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "twitch_apps" ADD "client_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "twitch_apps" ADD CONSTRAINT "UQ_e0b2f1ce39600aad6cf28187a9c" UNIQUE ("client_id")`);
        await queryRunner.query(`ALTER TABLE "twitch_apps" ADD "webhook_secret" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "twitch_apps" ADD "token_expires_at" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "twitch_apps" ADD "current_cost" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "twitch_apps" ADD "max_cost" integer NOT NULL DEFAULT '9000'`);
        await queryRunner.query(`ALTER TABLE "twitch_apps" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer_events" ADD "subscription_id" character varying`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer_events" ADD CONSTRAINT "UQ_e9e231b35cd0595caff4d764e4d" UNIQUE ("subscription_id")`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer_events" ADD "event_status" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer_events" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer" ADD "broadcaster_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer" ADD "twitch_login" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer" ADD CONSTRAINT "UQ_0cbf45d2070afe1b16d2aff5f16" UNIQUE ("twitch_login")`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer" ADD "display_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "display_name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ADD "public_credits_used" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "private_credits_used" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "discord_id" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_ecb6461da358b6d8a4f83d611a0" UNIQUE ("discord_id")`);
        await queryRunner.query(`ALTER TABLE "users" ADD "refresh_token" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "discord_access_token" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "discord_refresh_token" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "created_at" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "discord_notification_destinations" DROP CONSTRAINT "FK_3a0238d3f6b2c360e0889496dc9"`);
        await queryRunner.query(`ALTER TABLE "discord_notification_destinations" ALTER COLUMN "streamer_event_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer_events" DROP CONSTRAINT "FK_da0e3dcc3e1d212c321b3896f18"`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer_events" DROP CONSTRAINT "FK_c47002236e7f4235683b0a74f10"`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer_events" ALTER COLUMN "streamer_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer_events" ALTER COLUMN "twitch_app_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer_events" ADD CONSTRAINT "UQ_db4fb7f4d9d7ce6a32f0e858643" UNIQUE ("event", "streamer_id")`);
        await queryRunner.query(`ALTER TABLE "discord_notification_destinations" ADD CONSTRAINT "FK_3a0238d3f6b2c360e0889496dc9" FOREIGN KEY ("streamer_event_id") REFERENCES "twitch_streamer_events"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer_events" ADD CONSTRAINT "FK_da0e3dcc3e1d212c321b3896f18" FOREIGN KEY ("streamer_id") REFERENCES "twitch_streamer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer_events" ADD CONSTRAINT "FK_c47002236e7f4235683b0a74f10" FOREIGN KEY ("twitch_app_id") REFERENCES "twitch_apps"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "twitch_streamer_events" DROP CONSTRAINT "FK_c47002236e7f4235683b0a74f10"`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer_events" DROP CONSTRAINT "FK_da0e3dcc3e1d212c321b3896f18"`);
        await queryRunner.query(`ALTER TABLE "discord_notification_destinations" DROP CONSTRAINT "FK_3a0238d3f6b2c360e0889496dc9"`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer_events" DROP CONSTRAINT "UQ_db4fb7f4d9d7ce6a32f0e858643"`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer_events" ALTER COLUMN "twitch_app_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer_events" ALTER COLUMN "streamer_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer_events" ADD CONSTRAINT "FK_c47002236e7f4235683b0a74f10" FOREIGN KEY ("twitch_app_id") REFERENCES "twitch_apps"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer_events" ADD CONSTRAINT "FK_da0e3dcc3e1d212c321b3896f18" FOREIGN KEY ("streamer_id") REFERENCES "twitch_streamer"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "discord_notification_destinations" ALTER COLUMN "streamer_event_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "discord_notification_destinations" ADD CONSTRAINT "FK_3a0238d3f6b2c360e0889496dc9" FOREIGN KEY ("streamer_event_id") REFERENCES "twitch_streamer_events"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "discord_refresh_token"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "discord_access_token"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "refresh_token"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "UQ_ecb6461da358b6d8a4f83d611a0"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "discord_id"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "private_credits_used"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "public_credits_used"`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "display_name"`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer" DROP COLUMN "display_name"`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer" DROP CONSTRAINT "UQ_0cbf45d2070afe1b16d2aff5f16"`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer" DROP COLUMN "twitch_login"`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer" DROP COLUMN "broadcaster_id"`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer_events" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer_events" DROP COLUMN "event_status"`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer_events" DROP CONSTRAINT "UQ_e9e231b35cd0595caff4d764e4d"`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer_events" DROP COLUMN "subscription_id"`);
        await queryRunner.query(`ALTER TABLE "twitch_apps" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "twitch_apps" DROP COLUMN "max_cost"`);
        await queryRunner.query(`ALTER TABLE "twitch_apps" DROP COLUMN "current_cost"`);
        await queryRunner.query(`ALTER TABLE "twitch_apps" DROP COLUMN "token_expires_at"`);
        await queryRunner.query(`ALTER TABLE "twitch_apps" DROP COLUMN "webhook_secret"`);
        await queryRunner.query(`ALTER TABLE "twitch_apps" DROP CONSTRAINT "UQ_e0b2f1ce39600aad6cf28187a9c"`);
        await queryRunner.query(`ALTER TABLE "twitch_apps" DROP COLUMN "client_id"`);
        await queryRunner.query(`ALTER TABLE "discord_notification_destinations" DROP COLUMN "created_at"`);
        await queryRunner.query(`ALTER TABLE "discord_notification_destinations" DROP COLUMN "message_payload"`);
        await queryRunner.query(`ALTER TABLE "discord_notification_destinations" DROP COLUMN "webhook_url"`);
        await queryRunner.query(`ALTER TABLE "discord_notification_destinations" DROP COLUMN "guild_id"`);
        await queryRunner.query(`ALTER TABLE "discord_notification_destinations" DROP COLUMN "channel_id"`);
        await queryRunner.query(`ALTER TABLE "discord_notification_destinations" DROP COLUMN "credit_cost"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "privateCreditsUsed" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "publicCreditsUsed" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "users" ADD "discordRefreshToken" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "discordAccessToken" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ADD "refreshToken" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD "discordId" character varying`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "UQ_ae4a93a6b25195ccc2a97e13f0d" UNIQUE ("discordId")`);
        await queryRunner.query(`ALTER TABLE "users" ADD "displayName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer" ADD "broadcasterId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer" ADD "displayName" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer" ADD "twitchLogin" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer" ADD CONSTRAINT "UQ_2d84676a48249a92cf693422c26" UNIQUE ("twitchLogin")`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer_events" ADD "eventStatus" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer_events" ADD "twitchAppId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer_events" ADD "streamerId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer_events" ADD "subscriptionId" character varying`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer_events" ADD CONSTRAINT "UQ_b03926b83345af03988b91047ea" UNIQUE ("subscriptionId")`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer_events" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "twitch_apps" ADD "webhookSecret" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "twitch_apps" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "twitch_apps" ADD "maxCost" integer NOT NULL DEFAULT '9000'`);
        await queryRunner.query(`ALTER TABLE "twitch_apps" ADD "currentCost" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "twitch_apps" ADD "tokenExpiresAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "twitch_apps" ADD "clientId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "twitch_apps" ADD CONSTRAINT "UQ_25ea1660099082d7896311453fb" UNIQUE ("clientId")`);
        await queryRunner.query(`ALTER TABLE "discord_notification_destinations" ADD "creditCost" numeric(3,1) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "discord_notification_destinations" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "discord_notification_destinations" ADD "messagePayload" jsonb`);
        await queryRunner.query(`ALTER TABLE "discord_notification_destinations" ADD "webhookUrl" character varying`);
        await queryRunner.query(`ALTER TABLE "discord_notification_destinations" ADD "guildId" character varying`);
        await queryRunner.query(`ALTER TABLE "discord_notification_destinations" ADD "channelId" character varying`);
        await queryRunner.query(`ALTER TABLE "discord_notification_destinations" ADD "streamerEventId" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "twitch_streamer_events" ADD CONSTRAINT "UQ_1b150333a53b55767e13f367a8d" UNIQUE ("streamerId", "event")`);
    }

}
